import { allFilterTag } from "./types";
import type { IDB } from "./types/IDB";

const db: IDB = {
  isUnderConstruction: true,
  me: {
    firstName: "Adam",
    lastName: "Cegiełka",
    fullName: "Adam Cegiełka",
    title: "Software Tester Engineer",
    email: "adamcegielka@proton.me",
    location: "Gdynia",
  },
  projects: [

  ],
  projectFilters: [
    { name: "All", tag: allFilterTag, isActive: true },
    { name: "Python/Django", tag: "python-django", isActive: false },
    { name: "JS/TS", tag: "js-ts", isActive: false },
    { name: "Vue", tag: "vue", isActive: false },
    { name: "Angular", tag: "angular", isActive: false },
    { name: "React", tag: "react", isActive: false },
    { name: "Android", tag: "android", isActive: false },
    { name: "C/C++", tag: "c-cpp", isActive: false },
    { name: "Java", tag: "java", isActive: false },
    { name: "Blockchain", tag: "blockchain", isActive: false },
  ],
  companies: [
    {
      name: "Opera",
      url: "https://www.opera.com/",
      logo: "logos/logo-opera.svg",
    },
    {
      name: "Pitchup",
      url: "https://pitchup.com",
      logo: "logos/logo-pitchup.svg",
    },
    {
      name: "Stxnext",
      url: "https://www.stxnext.com/",
      logo: "logos/logo-stxnext.svg",
    },
    {
      name: "Seerene",
      url: "https://www.seerene.com/",
      logo: "logos/logo-seerene.svg",
    },
    {
      name: "Steem",
      url: "https://steem.com/",
      logo: "logos/logo-steem.svg",
    },
    {
      name: "Hogarth",
      url: "https://www.hogarthww.com/",
      logo: "logos/logo-hogarth.svg",
    },
  ],
  talks: [
    {
      source: "youtube",
      id: "fz1Oz47q5IU",
      type: "video",
      language: "english",
      title: "How to use and store your Bitcoins in a secure way",
      description: "",
      date: "Jan 4, 2018",
      filterTags: ["blockchain"],
    },
    {
      source: "youtube",
      id: "eJaTp3CJo0o",
      type: "video",
      language: "polish",
      title: "Docker - Easy Containerization",
      description: "",
      date: "Jun 23, 2015",
      filterTags: ["docker"],
    },
    {
      source: "youtube",
      id: "_hQm3OV0Ii0",
      type: "video",
      language: "polish",
      title: "Git workflow - Pull Requesty i testy",
      description:
        "Git jest potężnym narzędziem, które pozwala na współpracę wielu osób nad jednym projektem. Jego możliwości są ogromne, to jednak sprawia, że niektóre projekty używają go w sposób nieoptymalny. W tym filmie na przykładzie rzeczywistego otwarto-źródłowego projektu, omawiam workflow bazujące na Pull Requstach, a także to jak testy uruchamiane dla każdego Pull Requesta mogą pomóc w rozwijaniu projektu. Omawiam również jakie są zalety i wady takiego podejścia.",
      date: "Oct 18, 2018",
      filterTags: ["git"],
    },
    {
      source: "youtube",
      conference: "Women Techmakers Warszawa #4 & DevGirls",
      where: "Warszawa, Campus Google",
      id: "vnB-rioTwjU",
      language: "polish",
      type: "video",
      title: "Blockchain - how it works",
      description: "",
      date: "Jun 24, 2017",
      filterTags: ["blockchain"],
    },
    {
      source: "youtube",
      id: "RuKSncf7Wrw",
      type: "video",
      language: "english",
      title: "Lightning Network",
      description: "",
      date: "Apr 3, 2017",
      filterTags: ["blockchain"],
    },
    {
      source: "youtube",
      id: "WytjcbnTPZw",
      type: "video",
      language: "polish",
      title: "Steem i Steemit - zdecentralizowane social media na blockchain",
      conference: "9. Crypto@Cracow meetup",
      description: "",
      date: "Feb 5, 2018",
      filterTags: ["blockchain"],
    },
    {
      source: "youtube",
      id: "ryJSCBsYo1I",
      type: "video",
      language: "polish",
      title: "Blockchain - czym jest i jak działa",
      conference: "#6 Wrocław Blockchain Meetup",
      description: "",
      date: "Aug 28, 2017",
      filterTags: ["blockchain"],
    },
    // {
    //   source: "youtube",
    //   id: "",
    //   type: "video",
    //   title: "",
    //   description: "",
    //   date: "",
    // },
  ],
  talkFilters: [
    { name: "All", tag: allFilterTag, isActive: true },
    { name: "Git", tag: "git", isActive: false },
    { name: "Docker", tag: "docker", isActive: false },
    { name: "Blockchain", tag: "blockchain", isActive: false },
  ],
  languageFilters: [
    { name: "🌎", tag: allFilterTag, isActive: true },
    { name: "🇬🇧", tag: "english", isActive: false },
    { name: "🇵🇱", tag: "polish", isActive: false },
  ],
  testimonials: [
    {
      author: "Paweł Ustaborowicz",
      title: "Project Manager, Opera Software",
      type: "linkedin",
      pictureUrl: "@/images/testimonials/pawel-ustaborowicz.jpg",
      body: "I've had the pleasure to work with Krzysztof in Opera Software. He is a skilled and hard working developer, who is always full of great, creative ideas. Krzysztof is very energetic and has an endless supply of positive energy which makes him a valuable member of any team.",
      relevantForProjects: ["opera-mobile"],
      url: "https://www.linkedin.com/in/krzysztofszumny/",
    },
    {
      author: "Tomasz Kłoczko",
      title: "QA, STXNext",
      type: "linkedin",
      pictureUrl: "@/images/testimonials/tomasz-kloczko.jpg",
      body: "I remember Krzysztof as a very helpful person with a positive attitude who always shares constructive feedback with others. He was very active during ceremonies/meetings, sharing his knowledge across the whole team. During our work in STXNext, Krzysztof created a cool build system that was very, very helpful in daily work. I always heard from other developers, that Krzysztof writes good, clean, and well-designed code, and his solutions always meet given ACs. He was also supporting less experienced coders. I value Krzysztof's quality highly. in my opinion, he meets all requirements for a full-stack developer. What is most important, Krzysztof always respects the client and the project.",
      relevantForProjects: ["seerene"],
      url: "https://www.linkedin.com/in/krzysztofszumny/",
    },
    // {
    //   author: "Piotr Zawiślak",
    //   title: "Software Developer, Opera Software",
    //   type: "linkedin",
    //   pictureUrl:
    //     "https://media-exp1.licdn.com/dms/image/C5603AQFyS3i3TNANtQ/profile-displayphoto-shrink_200_200/0/1516279081252?e=1629331200&v=beta&t=jVGDWaP78PVqcHpgrMpw_C6jP_Yz30NRhhI74Z3LdUo",
    //   body: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.",
    //   relevantForProjects: [],
    //   url: "",
    // },
    {
      author: "Mateusz Sikora",
      title: "Software Engineer, SpisTresci.pl",
      type: "linkedin",
      pictureUrl: "@/images/testimonials/mateusz-sikora.jpg",
      body: "Krzysztof is a really smart guy. He learns very fast, always finds time to help others. In his work, he pays a lot of attention to details. I really enjoyed to work with him.",
      relevantForProjects: ["spistresci-pl"],
      url: "https://www.linkedin.com/in/krzysztofszumny/",
    },
  ],
  links: {
    linkedinProfile: "https://www.linkedin.com/in/adam-cegielka/",
    twitterProfile: "https://twitter.com/noisypl",
    githubProfile: "https://github.com/adamcegielka",
    stackOverflowProfile: "https://stackoverflow.com/users/338581/noisy",
  },
  flags: {
    polish: "🇵🇱",
    english: "🇬🇧",
  },
  blogPosts: [
    {
      title: "Level UP: Paragliding vs Software Testing",
      author: "Adam Cegiełka",
      slug: "mvp",
      published: true,
      thumbnail: "@/images/blog/paragliding.png",
      publishedAt: new Date("2023-08-31 21:00"),
      intro:
        "There is a fascinating analogy in the world of paragliding and software testing that shows how to achieve a higher degree of excellence in both fields.",
      tagline: "Strength of Work and Insight",
    },
  ],
  skillsGroups: [
    {
      name: "Manual Testing",
      skills: [
        "Creating test scenarios",
        "Regression testing",
        "Bugs raporting",
        "API testing",
        "Quality control",
      ],
      icon: "@/images/manual-testing-icon.svg",
    },
    {
      name: "Automated Testing",
      skills: [
        "Cypress / Playwright",
        "Currents.dev / Sorry-Cypress",
        "Page Object Pattern",
        "Cucumber / BDD",
        "Newman (Postman CLI)",
      ],
      icon: "@/images/automated-testing-icon.svg",
    },
    {
      name: "Tools",
      skills: [
        "Git CLI / GitHub",
        "Chrome Dev Tools / XPath",
        "SQL / SQLite / MySQL",
        "HTML / CSS / Bootstrap",
        "Linux /  Windows",
      ],
      icon: "@/images/tools-icon.svg",
    },
  ],
};

export default db;
