import { IDB } from "./types/IDB";

const db: IDB = {
  projects: [
    {
      name: "Campsite and holiday park booking website",
      slug: "pitchup.com",
      companyName: "Pitchup.com Ltd",
      thumbnail: "pitchup.com/thumbnail2.png",
      summaryTitle: "Progressive Web App for Pitchup.com",
      summary:
        "Mobile and off-line friendly web aplication design for Pitchup's users.",
      tags: ["python-django", "js-ts"],
      badges: ["Python", "Django"],
      technologies: [
        "javascript",
        "jquery",
        "typescript",
        "python",
        "django",
        "postgresql",
        "docker",
        "graphql",
        "stripe",
        "paypal",
        "git",
        "gitlab",
      ],
      thumbnailLogo: "logo-pitchup-mini.svg",
      featured: false,
      url: "https://pitchup.com/",
      archivedUrl: "",
      type: "Website",
    },
    {
      name: "Progressive Web App for Pitchup.com",
      slug: "pitchup-pwa",
      companyName: "Pitchup.com Ltd",
      thumbnail: "pitchup-pwa/thumbnail-1200.png",
      summaryTitle: "Progressive Web App for Pitchup.com",
      summary:
        "Mobile and off-line friendly web aplication design for Pitchup's users.",
      tags: ["vue", "js-ts"],
      badges: ["Vue", "TypeScript"],
      technologies: [
        "vue",
        "typescript",
        "graphql",
        "apollographql",
        "babeljs",
        "jestjs",
        "cypress",
        "git",
        "gitlab",
        "docker",
        "stripe",
      ],
      thumbnailLogo: "logo-pitchup-mini.svg",
      featured: true,
      url: "https://alfred.pitchup.dev/",
      archivedUrl: "",
      type: "Progressive Web Application",
    },
    {
      name: "Opera Mobile for Android",
      slug: "opera-mobile",
      url: "opera.com/mobile",
      archivedUrl:
        "https://web.archive.org/web/20110310200345/https://opera.com/mobile",
      type: "Mobile Application",
      companyName: "Opera Software",
      thumbnail: "opera-mobile.png",
      summaryTitle: "Example title",
      summary: "Opera Mobile was a mobile application for",
      tags: ["android", "java", "ccpp"],
      badges: ["Java", "C/C++", "Android", "Python"],
      technologies: ["android", "c", "cpp", "java"],
      thumbnailLogo: "logo-opera.svg",
      featured: true,
    },
    // {
    //   name: "Opera Max for Android",
    //   slug: "opera-max",
    //   companyName: "Opera Software",
    //   thumbnail: "opera-max.jpg",
    //   summaryTitle: "Example title",
    //   summary: "Data management and data saving app for Android",
    //   tags: ["android"],
    //   badges: ["Java", "C/C++", "Android"],
    //   thumbnailLogo: "logo-opera.svg",
    // },
    {
      name: "SpisTresci.pl",
      slug: "spistresci-pl",
      type: "Mobile Application",
      url: "",
      archivedUrl: "",
      companyName: "SpisTresci.pl",
      thumbnail: "spistresci.png",
      summaryTitle: "Example title",
      summary: "Description of a project",
      tags: ["python-django", "js-ts"],
      badges: ["Python", "Django", "jQuery"],
      technologies: ["python", "django", "jquery", "solr", "sqlalchemy"],
      thumbnailLogo: "spistresci.png",
      featured: true,
    },
    // {
    //   name: "Digital Asset Managment Platform",
    //   slug: "myzonza",
    //   companyName: "Hogarthww, through STXNext",
    //   thumbnail: "myzonza.png",
    //   summaryTitle: "Zonza & MyZonza",
    //   summary:
    //     "Asset Management Platform for the Enterprise, allowing businesses to store and manage materials in one cloud-based system",
    //   tags: ["python-django"],
    //   badges: ["Python", "Django", "Backbone.js"],
    //   thumbnailLogo: "logo-zonza.png",
    // },
    {
      name: "Seerene",
      slug: "seerene",
      companyName: "Seerene, via STXNext",
      thumbnail: "seerene/seerene-1.png",
      summaryTitle: "Seerene",
      summary:
        "An analytics platform that helps companies see how their other software is performing",
      tags: ["python-django", "angular", "js-ts"],
      badges: ["Python", "Django", "Angular"],
      technologies: [
        "python",
        "django",
        // "django-rest-framework",
        "javascript",
        "angular",
        "jenkins",
        // "cookiecutter",
        "docker",
        "postgresql",
        "jira",
        "git",
        "github",
      ],
      thumbnailLogo: "logo-seerene.svg",
      featured: false,
      url: "https://www.seerene.com/",
      archivedUrl: "",
      type: "Web Application + CLI tool",
    },
    // {
    //   name: "HiveProjects",
    //   slug: "hiveprojects",
    //   companyName: "HiveProjects",
    //   thumbnail: "hiveprojects.png",
    //   summaryTitle: "HiveProjects",
    //   summary:
    //     "Hive Projects is a directory of over a hundred apps, sites and tools built by Hive community. Your project is not listed here? You can add it on your own!",
    //   tags: ["python-django", "blockchain"],
    //   badges: ["Python", "Django", "blockchain"],
    //   thumbnailLogo: "hiveprojects.png",
    //   featured: true,
    // },
  ],
  projectFilters: [
    { name: "Python/Django", tag: ".python-django" },
    { name: "JS/TS", tag: ".js-ts" },
    { name: "Vue", tag: ".vue" },
    { name: "Angular", tag: ".angular" },
    { name: "React", tag: ".react" },
    { name: "Android", tag: ".android" },
    { name: "C/C++", tag: ".ccpp" },
    { name: "Java", tag: ".java" },
    { name: "Blockchain", tag: ".blockchain" },
  ],
  talks: [
    {
      source: "youtube",
      id: "fz1Oz47q5IU",
      type: "video",
      title: "How to use and store your Bitcoins in a secure way",
      description:
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus penatibus et magnis dis parturient montes, nascetur ridiculus mus..",
      date: "Jan 4, 2018",
    },
  ],
  testimonials: [
    {
      author: "Paweł Ustaborowicz",
      title: "Project Manager, Opera Software",
      type: "linkedin",
      pictureUrl:
        "https://media-exp1.licdn.com/dms/image/C5603AQG4EuUk13Vf0Q/profile-displayphoto-shrink_100_100/0/1516277136633?e=1626912000&v=beta&t=wFgJg724bKxY4QtqGwk4jLfKmJ_qa_lQkHDhLBcmoz8",
      body: "I've had the pleasure to work with Krzysztof in Opera Software. He is a skilled and hard working developer, who is always full of great, creative ideas. Krzysztof is very energetic and has an endless supply of positive energy which makes him a valuable member of any team.",
      relevantForProjects: ["opera-mobile"],
      url: "",
    },
    {
      author: "Tomasz Kłoczko",
      title: "QA, STXNext",
      type: "linkedin",
      pictureUrl:
        "https://media-exp1.licdn.com/dms/image/C4E03AQFLUNlcrSJn2g/profile-displayphoto-shrink_200_200/0/1517625984734?e=1629331200&v=beta&t=guTPmpV1coi0KnO0y9570mHM8lC1O8qATSgLz8We1zo",
      body: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.",
      relevantForProjects: ["seerene"],
      url: "",
    },
    {
      author: "Piotr Zawiślak",
      title: "Software Developer, Opera Software",
      type: "linkedin",
      pictureUrl:
        "https://media-exp1.licdn.com/dms/image/C5603AQFyS3i3TNANtQ/profile-displayphoto-shrink_200_200/0/1516279081252?e=1629331200&v=beta&t=jVGDWaP78PVqcHpgrMpw_C6jP_Yz30NRhhI74Z3LdUo",
      body: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.",
      relevantForProjects: [],
      url: "",
    },
  ],
  links: {
    linkedinProfile: "https://www.linkedin.com/in/krzysztofszumny/",
  },
  contactEmail: "hello@krzysztofszumny.com",
};

export default db;
